=== emxhive/prodex/schema/prodex.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$ref": "#/definitions/ProdexConfigFile",
    "definitions": {
        "ProdexConfigFile": {
            "type": "object",
            "properties": {
                "$schema": {
                    "type": "string"
                },
                "version": {
                    "type": "number"
                },
                "output": {
                    "$ref": "#/definitions/ProdexConfigFileOutput"
                },
                "exclude": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "aliases": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "depth": {
                    "type": "number"
                },
                "maxFiles": {
                    "type": "number"
                },
                "scopes": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/ProdexScope"
                    }
                }
            },
            "required": [
                "$schema",
                "version"
            ],
            "additionalProperties": false
        },
        "ProdexConfigFileOutput": {
            "type": "object",
            "properties": {
                "dir": {
                    "type": "string"
                },
                "versioned": {
                    "type": "boolean"
                },
                "format": {
                    "type": "string",
                    "enum": [
                        "md",
                        "txt"
                    ]
                }
            },
            "additionalProperties": false
        },
        "ProdexScope": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "entry": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "include": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "exclude": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "grep": {
                    "$ref": "#/definitions/ProdexGrepScopeConfig"
                }
            },
            "additionalProperties": false
        },
        "ProdexGrepScopeConfig": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string"
                },
                "any": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "all": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "regex": {
                    "type": "string"
                },
                "not": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "within": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "skip": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "additionalProperties": false
        }
    }
}

=== emxhive/prodex/prodex.json
{
    "version": 5,
    "$schema": "https://raw.githubusercontent.com/emxhive/prodex/main/schema/prodex.schema.json",
    "output": {
        "dir": "prodex@prodex",
        "versioned": true,
        "format": "md"
    },
    "aliases": {
        "@": "resources/js"
    },
    "depth": 10,
    "maxFiles": 200,
    "scopes": {
        "app": {
            "entry": [
                "src/index.ts"
            ]
        },
        "project": {
            "include": [
                ".github/**",
                "package.json",
                "prodex.json",
                "release-please-config.json",
                ".release-please-manifest.json",
                "CHANGELOG.md"
            ]
        }
    }
}
